### ISSUE TITLE
New Features for v2.1

### ISSUE THREAD

**Issue by mgarcia01752** [Comcast/Oscar#26]
#### SnmpTranslate NetSNMPGetDescription 
* Example: [NetSNMPGetDescription](https://github.com/Comcast/Oscar/blob/NetSNMPOIDDescription/src/com/comcast/oscar/examples/NetSNMPGetDescription.java)

#### MergeBulkBuild
* Example: [MergeConfigurationFileTemplates](https://github.com/Comcast/Oscar/blob/MergeBullkBuild/src/com/comcast/oscar/examples/MergeConfigurationFileTemplates.java)
* Usage: [Template-Merge-Bulk-Build](https://github.com/Comcast/Oscar/wiki/Template-Merge-Bulk-Build)

#### Configuration File Text Output
* Option for Dotted or Textual OID
* Example: [DottedTextualOutputFormatOption](https://github.com/Comcast/Oscar/blob/MergeBullkBuild/src/com/comcast/oscar/examples/DottedTextualOutputFormatOption.java)

**Comment by mgarcia01752** [comment]
#### TLV Comment Suppression 
* CLI option to suppress TLV Commments
* Example: [PrettyPrintSuppressTLVComment](https://github.com/Comcast/Oscar/blob/MergeBullkBuild/src/com/comcast/oscar/examples/PrettyPrintSuppressTLVComment.java)

**Comment by aflick** [comment]
MergeBulkBuild command complete

**Comment by aflick** [comment]
DottedTextualOutputFormatOption complete

**Comment by mgarcia01752** [comment]
Version 2.1
