### ISSUE TITLE
Incorrect DataType for SNMPv3NRUdpPortNumber

### ISSUE THREAD

**Issue by mgarcia01752** [Comcast/Oscar#3]
SNMPv3NotificationReceiver {
		SNMPv3NRIPv4Address 172.28.104.72;	 /* TLV: [38.1]*/
		SNMPv3NRUdpPortNumber 00:A2;	 /* TLV: [38.2]*/
		SNMPv3NRTrapType 00:02;	 /* TLV: [38.3]*/
		SNMPv3NRTimeout ;	 /* TLV: [38.4]*/
		SNMPv3NRRetries ;	 /* TLV: [38.5]*/
		SNMPv3NRFilteringParameters  null "Null";	 /* TLV: [38.6]*/
		SNMPv3NRSecurityName ;	 /* TLV: [38.7]*/
		SNMPv3NRIPv6Address ;	 /* TLV: [38.8]*/
	}

Should be a integer not Byte Array
		SNMPv3NRUdpPortNumber 00:A2;	 /* TLV: [38.2]*/

**Comment by aflick** [comment]
Fixed
