### ISSUE TITLE
Request to accept symbol + as a character value in a string

### ISSUE THREAD

**Issue by Bibhav** [Comcast/Oscar#42]
While compiling a text file to binary using oscar its observed that any vendor propitiatory string value containing the + symbol is compiled with warning message as below.

/* OSCAR -> OpenSource Cable modem file AssembleR v2.1.3.2 */
line 220:72 token recognition error at: '+'

String value used as part of config file is like the below sample : 
OctetString "xyyyyyzzz/xyzm/gYg+xyyxyyxy"

**Comment by mgarcia01752** [comment]
[Download Release 2.1.3.3-pre](https://github.com/Comcast/Oscar/releases/tag/2.1.3.3-pre)

Please verify fix.  Also make sure you remove the old DB file.
