### ISSUE TITLE
DB DataType Assignment Error

### ISSUE THREAD

**Issue by mgarcia01752** [Comcast/Oscar#8]
DownstreamPacketClassification	{
		 ClassifierReference 3;	 /* TLV: [23.1]*/
		 ServiceFlowReference 00:03;	 /* TLV: [23.3]*/
		 RulePriority 2;	 /* TLV: [23.5]*/
		 ClassifierActivationState 1;	 /* TLV: [23.6]*/
		 VendorSpecificClassifierParameters 08:03:FF:FF:FF:05:09:01:07:43:6F:6D:63:61:73:74;	 /* TLV: [23.43]*/
	}

ServiceFlowReference should be of type integer, not byte array

**Comment by aflick** [comment]
Fixed
